python src/compressed_sensing.py --net dd --dataset ffhq-69000 --input-type full-input --num-input-images 1 --batch-size 1 --image-size 256 --measurement-type circulant --noise-std 0.0 --num-measurements 5000 --model-type dd --no-annealed --mloss-weight -1 --zprior-weight -1 --zprior-sdev 1 --zprior-init-sdev 1.0 --max-update-iter 20000 --optimizer-type adam --learning-rate 0.04 --momentum 0. --num-random-restarts 1 --checkpoint-iter 1 --cuda 

python src/compressed_sensing.py --net dd --dataset ffhq-69000 --input-type full-input --num-input-images 1 --batch-size 1 --image-size 256 --measurement-type circulant --noise-std 0.0 --num-measurements 10000 --model-type dd --no-annealed --mloss-weight -1 --zprior-weight -1 --zprior-sdev 1 --zprior-init-sdev 1.0 --max-update-iter 10000 --optimizer-type adam --learning-rate 0.004 --momentum 0. --num-random-restarts 1 --checkpoint-iter 1 --cuda 

python src/compressed_sensing.py --net dd --dataset ffhq-69000 --input-type full-input --num-input-images 1 --batch-size 1 --image-size 256 --measurement-type circulant --noise-std 0.0 --num-measurements 15000 --model-type dd --no-annealed --mloss-weight -1 --zprior-weight -1 --zprior-sdev 1 --zprior-init-sdev 1.0 --max-update-iter 10000 --optimizer-type adam --learning-rate 0.004 --momentum 0. --num-random-restarts 1 --checkpoint-iter 1 --cuda 

python src/compressed_sensing.py --net dd --dataset ffhq-69000 --input-type full-input --num-input-images 1 --batch-size 1 --image-size 256 --measurement-type circulant --noise-std 0.0 --num-measurements 20000 --model-type dd --no-annealed --mloss-weight -1 --zprior-weight -1 --zprior-sdev 1 --zprior-init-sdev 1.0 --max-update-iter 10000 --optimizer-type adam --learning-rate 0.004 --momentum 0. --num-random-restarts 1 --checkpoint-iter 1 --cuda 

python src/compressed_sensing.py --net dd --dataset ffhq-69000 --input-type full-input --num-input-images 1 --batch-size 1 --image-size 256 --measurement-type circulant --noise-std 0.0 --num-measurements 40000 --model-type dd --no-annealed --mloss-weight -1 --zprior-weight -1 --zprior-sdev 1 --zprior-init-sdev 1.0 --max-update-iter 10000 --optimizer-type adam --learning-rate 0.004 --momentum 0. --num-random-restarts 1 --checkpoint-iter 1 --cuda 

python src/compressed_sensing.py --net dd --dataset ffhq-69000 --input-type full-input --num-input-images 1 --batch-size 1 --image-size 256 --measurement-type circulant --noise-std 0.0 --num-measurements 50000 --model-type dd --no-annealed --mloss-weight -1 --zprior-weight -1 --zprior-sdev 1 --zprior-init-sdev 1.0 --max-update-iter 10000 --optimizer-type adam --learning-rate 0.004 --momentum 0. --num-random-restarts 1 --checkpoint-iter 1 --cuda 

python src/compressed_sensing.py --net dd --dataset ffhq-69000 --input-type full-input --num-input-images 1 --batch-size 1 --image-size 256 --measurement-type circulant --noise-std 0.0 --num-measurements 75000 --model-type dd --no-annealed --mloss-weight -1 --zprior-weight -1 --zprior-sdev 1 --zprior-init-sdev 1.0 --max-update-iter 10000 --optimizer-type adam --learning-rate 0.004 --momentum 0. --num-random-restarts 1 --checkpoint-iter 1 --cuda 

python src/compressed_sensing.py --net dd --dataset ffhq-69000 --input-type full-input --num-input-images 1 --batch-size 1 --image-size 256 --measurement-type circulant --noise-std 0.0 --num-measurements 196608 --model-type dd --no-annealed --mloss-weight -1 --zprior-weight -1 --zprior-sdev 1 --zprior-init-sdev 1.0 --max-update-iter 10000 --optimizer-type adam --learning-rate 0.004 --momentum 0. --num-random-restarts 1 --checkpoint-iter 1 --cuda 

