python src/compressed_sensing.py --checkpoint-path ./checkpoints/glow/graph_unoptimized.pb --net glow --dataset celebA --num-input-images 1 --batch-size 1  --measurement-type circulant --noise-std 16.0 --num-measurements 2500 --model-type map --print-stats --checkpoint-iter 1 --cuda --mloss-weight -1 --learning-rate 0.001  --zprior-weight -1 --no-annealed --optimizer-type adam --max-update-iter 3000

python src/compressed_sensing.py --checkpoint-path ./checkpoints/glow/graph_unoptimized.pb --net glow --dataset celebA --num-input-images 1 --batch-size 1  --measurement-type circulant --noise-std 16.0 --num-measurements 5000 --model-type map --print-stats --checkpoint-iter 1 --cuda --mloss-weight -1 --learning-rate 0.001  --zprior-weight -1 --no-annealed --optimizer-type adam --max-update-iter 3000

python src/compressed_sensing.py --checkpoint-path ./checkpoints/glow/graph_unoptimized.pb --net glow --dataset celebA --num-input-images 1 --batch-size 1  --measurement-type circulant --noise-std 16.0 --num-measurements 10000 --model-type map --print-stats --checkpoint-iter 1 --cuda --mloss-weight -1 --learning-rate 0.001 --zprior-weight -1 --no-annealed --optimizer-type adam --max-update-iter 3000

python src/compressed_sensing.py --checkpoint-path ./checkpoints/glow/graph_unoptimized.pb --net glow --dataset celebA --num-input-images 1 --batch-size 1  --measurement-type circulant --noise-std 16.0 --num-measurements 20000 --model-type map --print-stats --checkpoint-iter 1 --cuda --mloss-weight -1 --learning-rate 0.001 --zprior-weight -1 --no-annealed --optimizer-type adam --max-update-iter 3000

python src/compressed_sensing.py --checkpoint-path ./checkpoints/glow/graph_unoptimized.pb --net glow --dataset celebA --num-input-images 1 --batch-size 1  --measurement-type circulant --noise-std 16.0 --num-measurements 30000 --model-type map --print-stats --checkpoint-iter 1 --cuda --mloss-weight -1 --learning-rate 0.001 --zprior-weight -1 --no-annealed --optimizer-type adam --max-update-iter 3000

python src/compressed_sensing.py --checkpoint-path ./checkpoints/glow/graph_unoptimized.pb --net glow --dataset celebA --num-input-images 1 --batch-size 1  --measurement-type circulant --noise-std 16.0 --num-measurements 35000 --model-type map --print-stats --checkpoint-iter 1 --cuda --mloss-weight -1 --learning-rate 0.001 --zprior-weight -1 --no-annealed --optimizer-type adam --max-update-iter 3000

